version: "3"
services:
  regtest:
    build:
      context: .
      dockerfile: Dockerfile
    image: "doichain/core"
    container_name: regtest
    environment:
      - REGTEST=true
      - RPC_ALLOW_IP=0.0.0.0/0
      - RPC_PASSWORD=adminpw
    ports:
      - "8338:8338"
      - "8339:8339"
      - "18332:18332"
    stdin_open: true
    volumes:
      - .:/.doichain/
    tty: true
    privileged: true
    networks:
      static:
        ipv4_address: 172.22.0.5

  electrumx-doi:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/electrumx
    image: "stallingerl/electrumx-doi"
    hostname: electrumx-doi
    volumes:
      - ./docker/startServer.sh:/home/electrumx/startServer.sh
    command: bash -c " ./startServer.sh"
    container_name: electrumx-doi
    ports:
      - "50001:50001"
      - "50002:50002"
      - "50004:50004"
    stdin_open: true
    tty: true
    privileged: true
    networks:
      static:
        ipv4_address: 172.22.0.6

networks:
  static:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1