services:
  regtest:
    image: "doichain/core:dc0.20.1.15"
    container_name: regtest
    ports:
      - "18332:18332"
      - "18443:18443"
      - "18445:18445"
    volumes:
      - ${DOICHAIN_DATA}:/home/doichain/.doichain/
      - ./doichain-regtest.conf:/home/doichain/.doichain/doichain.conf
    networks:
      - doichain_regtest-network

  electrumx:
    container_name: electrumx
    hostname: electrumx
    image: "doichain/electrumx:dc1.2.1"
    depends_on:
      - regtest
    volumes:
      - ${ELECTRUM_DB_VOLUME}:/home/doichain/.doichain/
      - ./db:/var/lib/electrumx
      - ./startElectrumDOIRegTest.sh:/startElectrumDOIRegTest.sh
    entrypoint: ["/startElectrumDOIRegTest.sh"]
    ports:
      - "50001:50001"
      - "50002:50002"
      - "8443:8443"
    stdin_open: true
    tty: true
    privileged: true
    networks:
      - doichain_regtest-network

  playwright:
    build:
      context: ${PLAYWRIGHT_BUILD_CONTEXT}
      dockerfile: ${PLAYWRIGHT_DOCKERFILE}
    container_name: playwright
    hostname: playwright
    ports:
      - "9323:9323"
    image: "doichain/playwright:latest"
    command: ${PLAYWRIGHT_COMMAND}
    stdin_open: true
    tty: true
    depends_on:
      - regtest
      - electrumx
    networks:
      - doichain_regtest-network

networks:
 doichain_regtest-network:
  driver: bridge
volumes:
  doichain:
  db:
  regtest: