services:
  regtest:
    image: "doichain/core:dc0.20.1.13"
    container_name: regtest
    ports:
      - "18332:18332"
      - "18443:18443"
      - "18445:18445"
    stdin_open: true
    volumes:
      - ./.doichain/:/home/doichain/.doichain/
      - ./doichain-regtest.conf:/home/doichain/data/doichain/doichain.conf
      - ./doichain-start.sh:/home/doichain/scripts/doichain-start.sh
    tty: true
    privileged: true
    command: "./scripts/start.sh"
    networks:
      - doichain_regtest-network

  electrumx-doi:
    container_name: electrumx-doi
    hostname: electrumx-doi
    image: "doichain/electrumx:dc1.2.1"
    depends_on:
      - regtest
    volumes:
      - ./db:/var/lib/electrumx
      - ./startElectrumDOIRegTest.sh:/startElectrumDOIRegTest.sh
    entrypoint: ["/startElectrumDOIRegTest.sh"]
    command: "/bin/bash"
    ports:
      - "50001:50001"
      - "50002:50002"
      - "8443:8443"
    stdin_open: true
    tty: true
    privileged: true
    networks:
      - doichain_regtest-network

networks:
  doichain_regtest-network:
    driver: bridge