services:
  regtest:
    image: "doichain/core:dc0.20.1.15"
    container_name: regtest
    ports:
      - "18332:18332"
      - "18443:18443"
      - "18445:18445"
    volumes:
      - ./.doichain/:/home/doichain/.doichain/
      - ./doichain-regtest.conf:/home/doichain/.doichain/doichain.conf
    networks:
      - doichain_regtest-network

  electrumx-doi:
    container_name: electrumx-doi
    hostname: electrumx-doi
    image: "doichain/electrumx:dc1.2.1"
    depends_on:
      - regtest
    volumes:
      - ./db:/var/lib/electrumx
      - ./startElectrumDOIRegTest.sh:/startElectrumDOIRegTest.sh
    entrypoint: ["/startElectrumDOIRegTest.sh"]
    ports:
      - "50001:50001"
      - "50002:50002"
      - "8080:8080"
      - "8443:8443"
    stdin_open: true
    tty: true
    privileged: true
    networks:
      - doichain_regtest-network

  playwright:
    build:
      context: ../../
      dockerfile: ./docker/doichain/playwright/Dockerfile
    container_name: playwright
    hostname: playwright
    ports:
      - "9323:9323"
    image: "doichain/playwright:latest"
    # command: ["npx", "playwright", "test"]
    command: ["echo", "finished building"]
    stdin_open: true
    tty: true
    depends_on:
      - regtest
      - electrumx-doi
    networks:
      - doichain_regtest-network
networks:
 doichain_regtest-network:
  driver: bridge
####end of file