services:
  mainnet:
     #build: .
     image: "doichain/core:dc0.20.1.13"
     container_name: doichain
     ports:
       - "8338:8338"
       - "8339:8339"
     stdin_open: true
     volumes:
       - ./.doichain/:/home/doichain/.doichain/
     environment:
      - RPC_ALLOW_IP=0.0.0.0/0
      - RPC_PASSWORD=adminpw
     tty: true
     privileged: true
#     entrypoint: ["/entrypoint.sh"]
     command: "/usr/local/bin/doichaind"
     networks:
       - doichain_network

  electrumx-nmc:
    container_name: electrumx-doi
    hostname: electrumx-doi
    image: "le-space/electrumx:dc1.2.1"
    depends_on:
      - doichain
    volumes:
      - ./db:/var/lib/electrumx
      - ./startElectrumDOI.sh:./startElectrumDOI.sh
    command: bash -c "./startElectrumDOI.sh
    ports:
      - "50001:50001"
      - "50002:50002"
      - "8443:8443"
    stdin_open: true
    tty: true
    privileged: true
    networks:
      - doichain_network
    environment:
      - COIN=Doichain
      - NET=mainnet
      - DB_DIRECTORY=/var/lib/electrumx
      - DAEMON_URL=http://admin:adminpw@doichain:8336
networks:
  doichain_network:
    driver: bridge