services:
  namecoin:
    build: .
    image: "inspiraluna/namecoin-core:latest"
    container_name: namecoin
    ports:
      - "8334:8334"
    stdin_open: true
    volumes:
      - ./.namecoin/:/home/namecoin/.namecoin/
      - ./entrypoint.sh:/entrypoint.sh
    tty: true
    privileged: true
    entrypoint: ["/entrypoint.sh"]
    command: "/usr/local/bin/namecoind"
    networks:
      static:
        ipv4_address: 172.22.0.4

  electrumx-nmc:
    build:
      dockerfile: ./Dockerfile
    working_dir: /home/electrumx
    image: "stallingerl/electrumx-doi"
    hostname: electrumx-nmc
    volumes:
      - ./startElectrumNMC.sh:/home/electrumx/startElectrumNMC.sh
    command: bash -c " ./startElectrumNMC.sh"
    container_name: electrumx-nmc
    ports:
      - "50001:50001"
      - "50002:50002"
      - "8443:8443"
    stdin_open: true
    tty: true
    privileged: true
    networks:
      static:
        ipv4_address: 172.22.0.6

networks:
  static:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1