services:
  namecoin:
    build: .
    image: "inspiraluna/namecoin-core:latest"
    container_name: namecoin
    ports:
      - "8335:8334"
      - "8336:8336"
    stdin_open: true
    volumes:
      - ./.namecoin/:/home/namecoin/.namecoin/
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - NAMECOIN_VER=nc27.1
    tty: true
    privileged: true
    entrypoint: ["/entrypoint.sh"]
    command: "/usr/local/bin/namecoind"
    networks:
      - namecoin_network

  electrumx-nmc:
    container_name: electrumx-nmc
    hostname: electrumx-nmc
    image: "le-space/electrumx"
    depends_on:
      - namecoin
    volumes:
      - ./db:/var/lib/electrumx
      - ./electrumx/startElectrumNMC.sh:/electrumx/startElectrumNMC.sh
    command: bash -c "./startElectrumNMC.sh"
    ports:
      - "50001:50001"
      - "50002:50002"
      - "8443:8443"
    stdin_open: true
    tty: true
    privileged: true
    networks:
      - namecoin_network
    environment:
      - COIN=Namecoin
      - NET=mainnet
      - DB_DIRECTORY=/var/lib/electrumx
      - DAEMON_URL=http://admin:adminpw@namecoin:8336

networks:
  namecoin_network:
    driver: bridge