name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Install Docker Compose
      uses: actions/checkout@v2
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    - name: Set up Docker
      run: docker-compose -f "docker/doichain/docker-compose-regtest.yml" up -d
    - uses: actions/setup-node@v4
      with:
           node-version: '20'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Start the development server
      run: npm run dev & npx wait-on http://localhost:5173
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: docker/healthcheck.sh regtest 120 && npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
